[package]
name = "phantomdev-tui"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true
keywords.workspace = true
categories.workspace = true
homepage.workspace = true

[dependencies]
phantomdev-core = { path = "../core", version = "0.1.0" }

tokio = { workspace = true, features = ["full"] }
serde.workspace = true
anyhow.workspace = true

ratatui.workspace = true
crossterm.workspace = true
